cities = {'Seatle': (0,0),
          'Portland': (1,1),
          'Helena': (1,3),
          'Bismark': (1,7),
          'Duluth': (1,10),
          'Mineapolis': (2,10),
          'Buffalo': (2,15),
          'Boston': (2,17),
          'Medford': (3,1),
          'Chicago': (3,13),
          'Salt Lake City': (4,4),
          'Omaha': (4,9),
          'New York City': (4,17),
          'Sacramento': (5,2),
          'Denver': (5,7),
          'Cincinati': (5,15),
          'Washington': (5,17),
          'San Fransisco': (6,2),
          'Kansas': (6,11),
          'St. Louis': (6,13),
          'Richmond': (7,18),
          'Santa Fe': (8,8),
          'Oklahoma City': (8,11),
          'Winston': (8,17),
          'Los Angeles': (9,5),
          'Phoenix': (9,5),
          'Memphis': (9,15),
          'San Diego': (10,6),
          'Dallas': (10,13),
          'Atlanta': (10,17),
          'Charleston': (10,19),
          'El Paso': (11,8),
          'Houston': (12,14),
          'New Orleans': (12,16),
          'Jacksonville': (12,19)}
